[tool.pdm]

[project]
name = "example-app-d"
version = "0.1.0"
description = "Package depending on example-app-c"
authors = [
    {name = "Nejc Skofic", email = "nejc.skofic@gmail.com"},
]
dependencies = [
    "example-app-c @ file:///${PROJECT_ROOT}/../c",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
